bot:
  name: rzd_check_seat_bot
  token: 7481028349:AAFWxgSy2YAivxSC8HXof4aSuG0rn8PEwVc

spring:
  application:
    name: rzdbot
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    hikari:
      schema: rzd
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yml